### ISSUE TITLE
玩家靠近告示牌并破坏告示牌导致卡退玩家客户端

### ISSUE THREAD

**Issue by yufengya0420** [Redbeanw44602/MovingLight#2]
玩家靠近告示牌并破坏告示牌导致卡退玩家客户端
LL版本：2.12.4，BDS版本：1.19.73，插件版本：1.9.2

**Comment by Redbeanw44602** [comment]
确定是movinglight问题吗

**Comment by yufengya0420** [comment]
基本可以确定，装了插件之后，有时候靠近告示牌，告示牌会消失看不见，离远一点又看见了，并且手机玩家有概率会因此卡退客户端，你可以自己用手机试试> 确定是movinglight问题吗
